# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A "hello world" function using the Armadillo library.
#'
#' @return
#' A 3x3 matrix with 7 on the diagonal and zero elsewhere.
#' @export
rcpparma_hello_world <- function() {
    .Call('RPackageTemplate_rcpparma_hello_world', PACKAGE = 'RPackageTemplate')
}

#' Calculates the inner product of a vector using the Armadillo library.
#'
#' @param x
#' A numeric vector of length \code{n}.
#' @return
#' The scalar \eqn{x'x}.
#' @export
rcpparma_innerproduct <- function(x) {
    .Call('RPackageTemplate_rcpparma_innerproduct', PACKAGE = 'RPackageTemplate', x)
}

#' Calculates the outer product of a vector using the Armadillo library.
#'
#' @param x
#' A numeric vector x of length \eqn{n}.
#' @return
#' The \eqn{nxn} matrix \eqn{xx'}.
#' @export
rcpparma_outerproduct <- function(x) {
    .Call('RPackageTemplate_rcpparma_outerproduct', PACKAGE = 'RPackageTemplate', x)
}

#' Calls both the inner and outer product functions, returning a list.
#'
#' @param x
#' A numeric vector of length \eqn{n}.
#' @return
#' A named list with two elements, the scalar inner and the matrix outer.
#' @export
rcpparma_bothproducts <- function(x) {
    .Call('RPackageTemplate_rcpparma_bothproducts', PACKAGE = 'RPackageTemplate', x)
}

